### ISSUE TITLE
PHP notice

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/submenu#2]
Plugin causes a PHP notice:

```
PHP Notice:  Trying to get property of non-object in /project/vendor/trendwerk/submenu/src/Submenu.php on line 19
```

**Comment by luukdv** [comment]
Can you give some context as to when this happened? For example on what type of page it occurred, how the lib was called, etc.

**Comment by sboerrigter** [comment]
After investigation I see that the notice is cause by the implementation 😳 . I'm sorry for this bug report.
